### ISSUE TITLE
Error: connection dropped

### ISSUE THREAD

**Issue by roseline124** [pinpoint-apm/pinpoint-node-agent#113]
I got 'Connection dropped' error log over and over again.

I'm using transport module 'THRIFT' in pinpoint server. 
I found the [0.6.0 had breaking changes](https://github.com/pinpoint-apm/pinpoint-node-agent/blob/5c686873c93e6155266484ae52d4d99410f9d05e/CHANGELOG.md#060---2020-6-26) that the protocol has been changed from Thrift to gRPC. Is relevant with this error? 

**info**

```
- pinpoint-node-agent version: 0.8.3
- transport module: 'THRIFT'
```

**error message**

```
requestApiMetaData err: Error: 14 UNAVAILABLE: Connection dropped
requestApiMetaData err: Error: 1 CANCELLED: Call cancelled
requestApiMetaData err: Error: 14 UNAVAILABLE: Connection dropped
requestApiMetaData err: Error: 1 CANCELLED: Call cancelled
requestApiMetaData err: Error: 14 UNAVAILABLE: Connection dropped
requestApiMetaData err: Error: 1 CANCELLED: Call cancelled
requestApiMetaData err: Error: 14 UNAVAILABLE: Connection dropped
requestApiMetaData err: Error: 1 CANCELLED: Call cancelled
requestApiMetaData err: Error: 14 UNAVAILABLE: Connection dropped
requestApiMetaData err: Error: 14 UNAVAILABLE: Connection dropped
requestApiMetaData err: Error: 14 UNAVAILABLE: Connection dropped
Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/home/node/app/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/node/app/node_modules/@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/home/node/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/home/node/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /home/node/app/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 14,
  details: 'Connection dropped',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
requestApiMetaData err: Error: 1 CANCELLED: Call cancelled
Error: 1 CANCELLED: Call cancelled
    at Object.callErrorFromStatus (/home/node/app/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/node/app/node_modules/@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/home/node/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/home/node/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /home/node/app/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 1,
  details: 'Call cancelled',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/home/node/app/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/node/app/node_modules/@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/home/node/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/home/node/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /home/node/app/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 14,
  details: 'Connection dropped',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

**pinpoint configuration on log**
```
[Pinpoint Agent] Configuration {
  serviceType: 1400,
  collectorIp: '-',
  collectorTcpPort: 9994,
  collectorStatPort: 9995,
  collectorSpanPort: 9996,
  sampling: true,
  sampleRate: 1,
  httpStatusCodeErrors: [ '5xx' ],
  logLevel: 'WARN',
  enabledDataSending: true,
  enabledStatsMonitor: true,
  enabledActiveThreadCount: false,
  express: true,
  koa: true,
  mongo: true,
  redis: true,
  enable: true,
  container: true,
  streamDeadlineMinutesClientSide: 10,
  agentId: '-',
  applicationName: '-'
}
```

**Comment by feelform** [comment]
The v0.8 Node agent sends App Information to Pinpoint server by [gRPC-JS](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js) modules.

**Comment by roseline124** [comment]
>The v0.8 Node agent sends App Information to Pinpoint server by [gRPC-JS](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js) modules.

then do I have to use previous version of v0.6?

**Comment by feelform** [comment]
v0.6 use gRPC native library. @roseline124 have to update to gRPC JS library. The gRPC native library is  deprecated

**Comment by feelform** [comment]
The Pinpoint Node agent use only support gRPC Pinpoint Collector server. 

Pinpoint Node agent v0.5 used THRIFT. But it is alpha status(unstable)

**Comment by roseline124** [comment]
Ok.. thank you for your answering :)
