### ISSUE TITLE
requestAgentInfo err: Error: 14 UNAVAILABLE: No connection established

### ISSUE THREAD

**Issue by Gopaljeepurwar** [pinpoint-apm/pinpoint-node-agent#89]
Getting below error while running demo app 
Node version:  v14.15.4
NPM version:  v6.14.10
Pinpoint node agent: v0.8.2

Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/Users/workspace/demo/node_modules/pinpoint-node-agent/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/workspace/demo/node_modules/pinpoint-node-agent/node_modules/@grpc/grpc-js/src/client.ts:338:36)
    at Object.onReceiveStatus (/Users/workspace/demo/node_modules/pinpoint-node-agent/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    at Object.onReceiveStatus (/Users/workspace/demo/node_modules/pinpoint-node-agent/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /Users/workspace/demo/node_modules/pinpoint-node-agent/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

**Comment by feelform** [comment]
@Gopaljeepurwar 
Could you check Pinpoint Collector server?
